export const SHEET_NAMES = {
  SETTINGS: 'SETTINGS',
  USERS: 'USERS',
  KELAS: 'KELAS',
  SISWA: 'SISWA',
  SESI: 'SESI',
  ABSENSI: 'ABSENSI',
  IZIN: 'IZIN',
  QR_HISTORY: 'QR_HISTORY',
  LOGS: 'LOGS',
  SYSTEM: 'SYSTEM',
};
